runtime: python311
instance_class: F1
service: plataforma-web-api-new
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker plataforma_web.app:app
env_variables:
  PROJECT_ID: justicia-digital-gob-mx
  SERVICE_PREFIX: plataforma_web_api
vpc_access_connector:
  name: projects/justicia-digital-gob-mx/locations/us-west2/connectors/cupido
