@api_key = {{$dotenv API_KEY}}
@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v3

### Bienvenida
GET {{root}}

### Audiencias
GET {{baseUrl}}/audiencias
X-Api-Key: {{api_key}}

### Audiencias de la autoridad 37
GET {{baseUrl}}/audiencias
    ?autoridad_id=37
X-Api-Key: {{api_key}}

### Audiencias de la autoridad SLT-J2-CIV
GET {{baseUrl}}/audiencias
    ?autoridad_clave=SLT-J2-CIV
X-Api-Key: {{api_key}}

### Audiencias de la autoridad SLT-J2-CIV del anio 2021
GET {{baseUrl}}/audiencias
    ?autoridad_clave=SLT-J2-CIV
    &anio=2021
X-Api-Key: {{api_key}}

### Audiencias de la autoridad SLT-J2-CIV de 2021-04-26
GET {{baseUrl}}/audiencias
    ?autoridad_clave=SLT-J2-CIV
    &fecha=2021-04-26
X-Api-Key: {{api_key}}

### Audiencias del Distrito de Monclova
GET {{baseUrl}}/audiencias
    ?distrito_clave=DMNC
    &fecha=2021-04-26
X-Api-Key: {{api_key}}

### Audiencia con id 58319
GET {{baseUrl}}/audiencias/58319
X-Api-Key: {{api_key}}
