@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v3

### Bienvenida
GET {{root}}

### Autoridades
GET {{baseUrl}}/autoridades

### Autoridades del Distrito Judicial de Saltillo id 6
GET {{baseUrl}}/autoridades
    ?distrito_id=6

### Autoridades del Distrito Judicial de Torreon DTRC
GET {{baseUrl}}/autoridades
    ?distrito_clave=dtrc

### Autoridades CEMASC
GET {{baseUrl}}/autoridades
    ?es_cemasc=true

### Autoridades creadoras de glosas
GET {{baseUrl}}/autoridades
    ?es_creador_glosas=true

### Autoridades Defensorias
GET {{baseUrl}}/autoridades
    ?es_defensoria=true

### Autoridades Jurisdiccionales
GET {{baseUrl}}/autoridades
    ?es_jurisdiccional=true

### Autoridades Jurisdiccionales sin Notarias
GET {{baseUrl}}/autoridades
    ?es_jurisdiccional=true
    &es_notaria=false

### Autoridades Notarias
GET {{baseUrl}}/autoridades
    ?es_notaria=true

### Autoridades Notarias en el Distrito Judicial de Monclova
GET {{baseUrl}}/autoridades
    ?distrito_clave=dmnc
    &es_notaria=true
