@api_key = {{$dotenv API_KEY}}
@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v3

### Bienvenida
GET {{root}}

### Distritos
GET {{baseUrl}}/distritos
X-Api-Key: {{api_key}}

### Distritos es_distrito_judicial
GET {{baseUrl}}/distritos
    ?es_distrito_judicial=true
X-Api-Key: {{api_key}}

### Distritos es_distrito
GET {{baseUrl}}/distritos
    ?es_distrito=true
X-Api-Key: {{api_key}}

### Distritos es_jurisdiccional
GET {{baseUrl}}/distritos
    ?es_jurisdiccional=true
X-Api-Key: {{api_key}}

### Distrito Torreon
GET {{baseUrl}}/distritos/dtrc
X-Api-Key: {{api_key}}
