@api_key = {{$dotenv API_KEY}}
@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v3

### Bienvenida
GET {{root}}

### Edictos
GET {{baseUrl}}/edictos

### Edictos de la autoridad 37
GET {{baseUrl}}/edictos
    ?autoridad_id=37

### Edictos del SLT-J2-CIV
GET {{baseUrl}}/edictos
    ?autoridad_clave=SLT-J2-CIV

### Edictos del SLT-J2-CIV del 2021
GET {{baseUrl}}/edictos
    ?autoridad_clave=SLT-J2-CIV
    &anio=2021

### Edictos del SLT-J2-CIV del 2021-04-26
GET {{baseUrl}}/edictos
    ?autoridad_clave=SLT-J2-CIV
    &fecha=2021-04-26

### Edictos del distrito DMNC
GET {{baseUrl}}/edictos
    ?distrito_clave=DMNC

### Edictos del distrito DMNC del 2022-03-01 al 2022-03-31
GET {{baseUrl}}/edictos
    ?distrito_clave=DMNC
    &fecha_desde=2022-03-01
    &fecha_hasta=2022-03-31

### Edicto con id 49367
GET {{baseUrl}}/edictos/49367
