@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v3

### Bienvenida
GET {{root}}

### Redams
GET {{baseUrl}}/redam

### Redams con nombre Luis
GET {{baseUrl}}/redam
    ?nombre=Luis

### Redams con un nombre que no existe
GET {{baseUrl}}/redam
    ?nombre=EsteNombreNOExiste

### Redams con expediente 1195/2018
GET {{baseUrl}}/redam
    ?expediente=1195/2018

### Redams del TRC-J2-FAM
GET {{baseUrl}}/redam
    ?autoridad_clave=TRC-J2-FAM

### Redams del distrito DTRC
GET {{baseUrl}}/redam
    ?distrito_clave=DTRC

### Redam con id 13
GET {{baseUrl}}/redam/13
