@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v3

### Bienvenida
GET {{root}}

### REDAM
GET {{baseUrl}}/redam

### REDAM con nombre Luis
GET {{baseUrl}}/redam
    ?nombre=Luis

### REDAM con un nombre que no existe
GET {{baseUrl}}/redam
    ?nombre=EsteNombreNOExiste

### REDAM con expediente 1195/2018
GET {{baseUrl}}/redam
    ?expediente=1195/2018

### REDAM del TRC-J2-FAM
GET {{baseUrl}}/redam
    ?autoridad_clave=TRC-J2-FAM

### REDAM del distrito DTRC
GET {{baseUrl}}/redam
    ?distrito_clave=DTRC

### REDAM con id 13
GET {{baseUrl}}/redam/13
