@api_key = {{$dotenv API_KEY}}
@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v3

### Bienvenida
GET {{root}}

### REPSVM Agresores
GET {{baseUrl}}/repsvm_agresores/paginado
X-Api-Key: {{api_key}}

### REPSVM Agresores con nombre Luis
GET {{baseUrl}}/repsvm_agresores/paginado
    ?nombre=Luis
X-Api-Key: {{api_key}}

### REPSVM Agresores con un nombre que no existe
GET {{baseUrl}}/repsvm_agresores/paginado
    ?nombre=EsteNombreNOExiste
X-Api-Key: {{api_key}}

### REPSVM Agresores del distrito DRGR
GET {{baseUrl}}/repsvm_agresores/paginado
    ?distrito_clave=DRGR
X-Api-Key: {{api_key}}

### REPSVM Agresor con id 955
GET {{baseUrl}}/repsvm_agresores/955
X-Api-Key: {{api_key}}
