@api_key = {{$dotenv API_KEY}}
@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v3

### Bienvenida
GET {{root}}

### Epocas
GET {{baseUrl}}/epocas

### Epoca con id 1
GET {{baseUrl}}/epocas/1

### Tesis Jurisprudencias
GET {{baseUrl}}/tesis_jurisprudencias

### Tesis Jurisprudencia con id 1
GET {{baseUrl}}/tesis_jurisprudencias/1

### Tesis Jurisprudencias de la autoridad con clave TRC-SR
GET {{baseUrl}}/tesis_jurisprudencias
    ?autoridad_clave=TRC-SR

### Tesis Jurisprudencias de la epoca con id 1
GET {{baseUrl}}/tesis_jurisprudencias
    ?epoca_id=1

### Tesis Jurisprudencias de la materia con id 2
GET {{baseUrl}}/tesis_jurisprudencias
    ?materia_id=2
