
### Glosas
GET {{baseUrl}}/glosas
X-Api-Key: {{apiKey}}

### Glosas de la autoridad 106
GET {{baseUrl}}/glosas
    ?autoridad_id=106
X-Api-Key: {{apiKey}}

### Glosas del Pleno del Tribunal Constitucional
GET {{baseUrl}}/glosas
    ?autoridad_clave=PTC
X-Api-Key: {{apiKey}}

### Glosas del Pleno del Tribunal Constitucional del 2022
GET {{baseUrl}}/glosas
    ?autoridad_clave=PTC
    &anio=2022
X-Api-Key: {{apiKey}}

### Glosas del 2022-07-14
GET {{baseUrl}}/glosas
    ?fecha=2022-07-14
X-Api-Key: {{apiKey}}

### Glosas del Pleno del Tribunal Constitucional expediente 5/2021-AIL
GET {{baseUrl}}/glosas
    ?autoridad_clave=PTC
    &expediente=5/2021-AIL
X-Api-Key: {{apiKey}}

### Detalle de la glosa con id 1940
GET {{baseUrl}}/glosas/1940
X-Api-Key: {{apiKey}}
