
### Tipos de Juicios
GET {{baseUrl}}/materias_tipos_juicios
X-Api-Key: {{apiKey}}

### Tipos de Juicios de la materia Familiar
GET {{baseUrl}}/materias_tipos_juicios
    ?materia_clave=fam
X-Api-Key: {{apiKey}}

### Tipos de Juicios de la materia Familiar
GET {{baseUrl}}/materias_tipos_juicios
    ?materia_id=3
X-Api-Key: {{apiKey}}

### Tipo de Juicio CIVIL HIPOTECARIO
GET {{baseUrl}}/materias_tipos_juicios/60
X-Api-Key: {{apiKey}}
